package main

import (
	"path"
	"strconv"

	"google.golang.org/protobuf/compiler/protogen"
)

func generateTs(p *protogen.Plugin, pac *Package) error {
	if len(pac.Events) == 0 {
		return nil
	}

	filename := path.Join(pac.OutDir, "registry.ts")
	g := p.NewGeneratedFile(filename, pac.GoImport)

	g.P("// Code generated by protoc-gen-event-registry. DO NOT EDIT.")
	g.P("// source package: ", pac.GoImport)
	g.P()

	// getSource(namespace)
	g.P("export function getSource(namespace: string): string {")
	g.P("  const suffix = ", strconv.Quote(pac.SourceSuffix), ";")
	g.P("  if (!suffix) { return namespace; }")
	g.P("  if (!namespace) { return suffix; }")
	g.P("  return `${namespace}.${suffix}`;")
	g.P("}")
	g.P()

	// One const per event: <MessageName>DetailType = "<detailType>"
	for _, e := range pac.Events {
		constName := DotToPascal(e.DetailType) + "DetailType"
		g.P("export const ", constName, " = ", strconv.Quote(e.DetailType), " as const;")
	}

	return nil
}
