package main

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func generateGo(p *protogen.Plugin, pac *Package) error {
	if len(pac.Events) == 0 {
		return nil
	}

	filename := path.Join(pac.OutDir, "registry.go")
	g := p.NewGeneratedFile(filename, pac.GoImport)

	g.P("// Code generated by protoc-gen-event-registry. DO NOT EDIT.")
	g.P("package ", pac.GoPackage)
	g.P()
	g.P("import (")
	g.P(`"fmt"`)
	g.P(`ebtypes "github.com/aws/aws-sdk-go-v2/service/eventbridge/types"`)
	g.P(`"google.golang.org/protobuf/encoding/protojson"`)
	g.P(")")
	g.P()
	g.P("var marshalOpts = protojson.MarshalOptions{")
	g.P("	UseEnumNumbers: true,")
	g.P("}")
	g.P()
	g.P()

	// One helper per event, named from DetailType.
	// Example: DetailType "foo.bar" -> BuildFooBarEvent(...)
	usedNames := map[string]int{}
	for _, e := range pac.Events {
		baseName := "Build" + DotToPascal(e.DetailType) + "Event"
		fnName := baseName
		usedNames[baseName]++
		if usedNames[baseName] > 1 {
			// Extremely unlikely unless two events DotToPascal() to the same value.
			fnName = fmt.Sprintf("%s%d", baseName, usedNames[baseName])
		}

		constName := DotToPascal(e.DetailType) + "DetailType"

		g.P("func ", fnName, "(eventBusName *string, sourcePrefix string, message *", g.QualifiedGoIdent(e.Message.GoIdent), ") (ebtypes.PutEventsRequestEntry, error) {")
		g.P("	if message == nil {")
		g.P(`		return ebtypes.PutEventsRequestEntry{}, fmt.Errorf("nil message for detailType %s", `, constName, ")")
		g.P("	}")
		g.P("	b, err := marshalOpts.Marshal(message)")
		g.P("	if err != nil { return ebtypes.PutEventsRequestEntry{}, err }")
		g.P("	src := GetSource(sourcePrefix)")
		g.P("	return ebtypes.PutEventsRequestEntry{")
		g.P("		Detail:       new(string(b)),")
		g.P("		DetailType:   new(", constName, "),")
		g.P("		Source:       new(src),")
		g.P("		EventBusName: eventBusName,")
		g.P("	}, nil")
		g.P("}")
		g.P()
	}

	g.P("func GetSource(namespace string) string {")
	g.P(`  suffix := "`, strings.TrimSpace(pac.SourceSuffix), `"`)
	g.P("  if suffix == \"\" {")
	g.P("    return namespace")
	g.P("  }")
	g.P("  if namespace == \"\" {")
	g.P("    return suffix")
	g.P("  }")
	g.P("  return namespace + \".\" + suffix")
	g.P("}")
	g.P()

	g.P("const (")
	for _, e := range pac.Events {
		constName := DotToPascal(e.DetailType) + "DetailType"
		g.P("  ", constName, ` = "`, e.DetailType, `"`)
	}
	g.P(")")

	return nil
}
