package main

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func generateSfnStepsTs(p *protogen.Plugin, pac *Package) error {
	if len(pac.Events) == 0 {
		return nil
	}

	// Normalize source suffix: allow "", "identity.customer", ".identity.customer"
	sourceSuffix := strings.TrimSpace(pac.SourceSuffix)
	if sourceSuffix != "" && !strings.HasPrefix(sourceSuffix, ".") {
		sourceSuffix = "." + sourceSuffix
	}

	outDir := path.Join(pac.OutDir, "stepfunctions")

	for _, ev := range pac.Events {
		detailType := strings.TrimSpace(ev.DetailType)
		if detailType == "" {
			detailType = string(ev.Message.Desc.Name())
		}

		fileBase := safeFileName(detailType)
		filename := path.Join(outDir, fileBase+".ts")
		g := p.NewGeneratedFile(filename, "")

		// Names
		eventNamePascal := pascalFromDetailType(detailType) // user.created -> UserCreated
		detailTypeName := eventNamePascal + "Detail"
		propsTypeName := "Emit" + eventNamePascal + "EventTaskProps"
		fnName := "emit" + eventNamePascal + "Event"

		// Header / imports
		g.P("/* Code generated by protoc-gen-event-registry (stepfunctions); DO NOT EDIT. */")
		g.P("")
		g.P(`import { Construct } from "constructs";`)
		g.P(`import { CallAwsService } from "aws-cdk-lib/aws-stepfunctions-tasks";`)
		g.P("")

		emitJsonataHelpers(g)

		// Detail type: fixed keys, values JsonataValue (or JsonataValue[] if repeated)
		g.P(fmt.Sprintf("export type %s = {", detailTypeName))
		emitDetailTypeJsonata(g, ev.Message)
		g.P("};")
		g.P("")

		// Props: requires detail
		g.P(fmt.Sprintf("export interface %s {", propsTypeName))
		g.P("  /** EventBridge global endpoint id (optional if you don't use endpoints) */")
		g.P("  readonly endpointId?: string;")
		g.P("  /** Target event bus name */")
		g.P("  readonly eventBusName: string;")
		g.P("  /** Prefix for Source, e.g. namespace string */")
		g.P("  readonly sourcePrefix: string;")
		g.P("  /** Type-safe detail payload (keys fixed by the event message) */")
		g.P(fmt.Sprintf("  readonly detail: %s | string;", detailTypeName))
		g.P("  /** Override iamResources (defaults to ['*']) */")
		g.P("  readonly iamResources?: string[];")
		g.P("}")
		g.P("")

		// Function (JSONata)
		g.P(fmt.Sprintf("export function %s(scope: Construct, id: string, props: %s): CallAwsService {", fnName, propsTypeName))
		g.P("  return CallAwsService.jsonata(scope, id, {")
		g.P(`    service: "eventbridge",`)
		g.P(`    action: "putEvents",`)
		g.P(`    iamResources: props.iamResources ?? ["*"],`)
		g.P("    parameters: {")
		g.P("      ...(props.endpointId ? { EndpointId: props.endpointId } : {}),")
		g.P("      Entries: [")
		g.P("        {")
		g.P("          EventBusName: props.eventBusName,")
		g.P(fmt.Sprintf("          Source: `${props.sourcePrefix}%s`,", escapeTemplateLiteral(sourceSuffix)))
		g.P(fmt.Sprintf("          DetailType: %q,", detailType))
		g.P("          // PutEvents expects Detail as a JSON string; build it via JSONata $string(...)")
		g.P("          Detail: toJsonataJsonString(props.detail),")
		g.P("        },")
		g.P("      ],")
		g.P("    },")
		g.P("    // Equivalent of \"discard result\": pass through original state input")
		g.P(`    outputs: "{% $states.input %}",`)
		g.P("  });")
		g.P("}")
		g.P("")
	}

	return nil
}

func emitJsonataHelpers(g *protogen.GeneratedFile) {
	g.P("export type JsonataValue =")
	g.P("  | string")
	g.P("  | number")
	g.P("  | boolean")
	g.P("  | null")
	g.P("  | { [key: string]: JsonataValue }")
	g.P("  | JsonataValue[];")
	g.P("")

	g.P("/**")
	g.P(" * If a string is wrapped in \"{% ... %}\", treat it as a raw JSONata expression.")
	g.P(" * Otherwise treat it as a JSON string literal.")
	g.P(" */")
	g.P("function asJsonataExpr(v: JsonataValue): string {")
	g.P("  if (v === null) return \"null\";")
	g.P("  if (typeof v === \"number\" || typeof v === \"boolean\") return String(v);")
	g.P("")
	g.P("  if (typeof v === \"string\") {")
	g.P("    const m = v.match(/^\\s*\\{%\\s*([\\s\\S]*?)\\s*%\\}\\s*$/);")
	g.P("    if (m) return `(${m[1]})`;")
	g.P("    return JSON.stringify(v);")
	g.P("  }")
	g.P("")
	g.P("  if (Array.isArray(v)) {")
	g.P("    return `[${v.map(asJsonataExpr).join(\", \")}]`;")
	g.P("  }")
	g.P("")
	g.P("  // object")
	g.P("  const keys = Object.keys(v).sort();")
	g.P("  const entries = keys.map((k) => `${JSON.stringify(k)}: ${asJsonataExpr((v as any)[k])}`);")
	g.P("  return `{${entries.join(\", \")}}`;")
	g.P("}")
	g.P("")

	g.P("/**")
	g.P(" * Build a JSONata expression string that evaluates to a JSON string")
	g.P(" * of the provided (possibly expression-containing) value.")
	g.P(" */")
	g.P("function toJsonataJsonString(v: JsonataValue): string {")
	g.P("  return `{% $string(${asJsonataExpr(v)}) %}`;")
	g.P("}")
	g.P("")
}

func emitDetailTypeJsonata(g *protogen.GeneratedFile, msg *protogen.Message) {
	// Make output deterministic by sorting by JSON name
	type fieldOut struct {
		jsonName string
		repeated bool
		optional bool
	}
	fields := make([]fieldOut, 0, len(msg.Fields))
	for _, f := range msg.Fields {
		fields = append(fields, fieldOut{
			jsonName: f.Desc.JSONName(),
			repeated: f.Desc.Cardinality() == protoreflect.Repeated,
			optional: isOptionalFieldJsonata(f),
		})
	}
	sort.Slice(fields, func(i, j int) bool { return fields[i].jsonName < fields[j].jsonName })

	for _, fo := range fields {
		tsType := "JsonataValue"
		if fo.repeated {
			tsType = "JsonataValue[]"
		}
		if fo.optional {
			g.P(fmt.Sprintf("  %q?: %s;", fo.jsonName, tsType))
		} else {
			g.P(fmt.Sprintf("  %q: %s;", fo.jsonName, tsType))
		}
	}
}

func isOptionalFieldJsonata(f *protogen.Field) bool {
	// Repeated fields aren't "optional" in TS here.
	if f.Desc.Cardinality() == protoreflect.Repeated {
		return false
	}
	// Presence => may be omitted
	return f.Desc.HasPresence()
}

// --- helpers (same as before) ---

func safeFileName(detailType string) string {
	s := strings.ToLower(strings.TrimSpace(detailType))
	s = strings.ReplaceAll(s, ".", "-")
	s = strings.ReplaceAll(s, " ", "-")
	re := regexp.MustCompile(`[^a-z0-9\-_]+`)
	s = re.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if s == "" {
		return "event"
	}
	return s
}

func pascalFromDetailType(detailType string) string {
	parts := splitNonAlnum(detailType)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	out := b.String()
	if out == "" {
		return "Event"
	}
	return out
}

func splitNonAlnum(s string) []string {
	re := regexp.MustCompile(`[^a-zA-Z0-9]+`)
	return re.Split(strings.TrimSpace(s), -1)
}

func escapeTemplateLiteral(s string) string {
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return s
}
